# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keel < Formula
  desc "Opinionated Go framework CLI for building structured services"
  homepage "https://keel-go.dev"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slice-soft/keel/releases/download/v1.2.1/keel_darwin_amd64.tar.gz"
      sha256 "6f508a3f799aac2f98d34bd80fccd90b025523fec87b2e36e398372fe9d56d0f"

      define_method(:install) do
        bin.install "keel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slice-soft/keel/releases/download/v1.2.1/keel_darwin_arm64.tar.gz"
      sha256 "0ba8bfc99c55f4db8d18eb7f2ba78df97cae3eb1d9abeea004af8f207c293d42"

      define_method(:install) do
        bin.install "keel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slice-soft/keel/releases/download/v1.2.1/keel_linux_amd64.tar.gz"
      sha256 "1ebcdbbf12dc17d97ddc991fb28f099ee7e99e4e31b2a10a730925510dccf6ee"
      define_method(:install) do
        bin.install "keel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slice-soft/keel/releases/download/v1.2.1/keel_linux_arm64.tar.gz"
      sha256 "6c0861c5792d4d116a1b645203acf8cfbe89f47e23c39100729aff0e9573688a"
      define_method(:install) do
        bin.install "keel"
      end
    end
  end

  test do
    system "#{bin}/keel", "--version"
  end
end
