# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keel < Formula
  desc "Opinionated Go framework CLI for building structured services"
  homepage "https://keel-go.dev"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slice-soft/keel/releases/download/v1.5.0/keel_darwin_amd64.tar.gz"
      sha256 "7e8faaa832e7fe3b6d62e3e371fad4079f871d1b5c3e024c424eada684665f41"

      define_method(:install) do
        bin.install "keel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slice-soft/keel/releases/download/v1.5.0/keel_darwin_arm64.tar.gz"
      sha256 "de288994bdfc9be2cf9bf8a2adbde879bf082e07beed49c1cddcb9897f1d5a86"

      define_method(:install) do
        bin.install "keel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slice-soft/keel/releases/download/v1.5.0/keel_linux_amd64.tar.gz"
      sha256 "bcfdccd5d1138f1f2152bce5bb4b6c3997e22edbee73f30d1f747e679d0f9dd4"
      define_method(:install) do
        bin.install "keel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slice-soft/keel/releases/download/v1.5.0/keel_linux_arm64.tar.gz"
      sha256 "73b9284d9abfb3a1fb96d849a67628524a04b2149c465131a462441139568e99"
      define_method(:install) do
        bin.install "keel"
      end
    end
  end

  test do
    system "#{bin}/keel", "--version"
  end
end
